# Generated by Django 5.2.8 on 2025-11-10 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_locks', to='api.seat')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_locks', to='api.trip')),
            ],
            options={
                'indexes': [models.Index(fields=['trip', 'seat'], name='api_seatloc_trip_id_8d151a_idx'), models.Index(fields=['expires_at'], name='api_seatloc_expires_9ba4a5_idx')],
                'unique_together': {('trip', 'seat')},
            },
        ),
    ]
