# Generated by Django 5.2.8 on 2025-11-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_seatlock'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='insurance_company',
            field=models.CharField(blank=True, default='Нэйшнл эженси', max_length=100),
        ),
        migrations.AddField(
            model_name='bus',
            name='insurance_fee',
            field=models.DecimalField(decimal_places=2, default=1600.0, max_digits=10),
        ),
    ]
